version: "3"

services:
    next-app:
        container_name: english-toeic-frontend
        build:
            context: ./
            target: runner
            dockerfile: Dockerfile
        restart: always
        ports:
            - 3000:3000
        env_file:
            - .env.local
        environment:
            - NODE_ENV=production
        networks:
            - english-toeic-network
